//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceCore.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comanda
    {
        public int ComandaId { get; set; }
        public int AutoId { get; set; }
        public int ClientId { get; set; }
        public string StareComanda { get; set; }
        public System.DateTime DataSystem { get; set; }
        public Nullable<System.DateTime> DataProgramare { get; set; }
        public Nullable<System.DateTime> DataFinalizare { get; set; }
        public int KmBord { get; set; }
        public string Descriere { get; set; }
        public decimal ValoarePiese { get; set; }
    
        public virtual Automobil Automobil { get; set; }
        public virtual Client Client { get; set; }
    }
}
