//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceCore.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagine
    {
        public int ImagineId { get; set; }
        public string Titlu { get; set; }
        public string Descriere { get; set; }
        public System.DateTime DataImagine { get; set; }
        public byte[] Foto { get; set; }
    }
}
