//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceCore.Context
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sasiu", Namespace="http://schemas.datacontract.org/2004/07/CarServiceCore.Context", IsReference=true)]
    public partial class Sasiu : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodSasiuField;
        
        private string DenumireField;
        
        private int SasiuIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodSasiu
        {
            get
            {
                return this.CodSasiuField;
            }
            set
            {
                this.CodSasiuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire
        {
            get
            {
                return this.DenumireField;
            }
            set
            {
                this.DenumireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SasiuId
        {
            get
            {
                return this.SasiuIdField;
            }
            set
            {
                this.SasiuIdField = value;
            }
        }
    }
    
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IChassisService")]
public interface IChassisService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChassisService/ChassisExists", ReplyAction="http://tempuri.org/IChassisService/ChassisExistsResponse")]
    bool ChassisExists(CarServiceCore.Context.Sasiu chassis);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChassisService/ChassisExists", ReplyAction="http://tempuri.org/IChassisService/ChassisExistsResponse")]
    System.Threading.Tasks.Task<bool> ChassisExistsAsync(CarServiceCore.Context.Sasiu chassis);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChassisService/GetAllChassis", ReplyAction="http://tempuri.org/IChassisService/GetAllChassisResponse")]
    CarServiceCore.Context.Sasiu[] GetAllChassis();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChassisService/GetAllChassis", ReplyAction="http://tempuri.org/IChassisService/GetAllChassisResponse")]
    System.Threading.Tasks.Task<CarServiceCore.Context.Sasiu[]> GetAllChassisAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChassisService/GetChassis", ReplyAction="http://tempuri.org/IChassisService/GetChassisResponse")]
    CarServiceCore.Context.Sasiu GetChassis(int chassisId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChassisService/GetChassis", ReplyAction="http://tempuri.org/IChassisService/GetChassisResponse")]
    System.Threading.Tasks.Task<CarServiceCore.Context.Sasiu> GetChassisAsync(int chassisId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChassisService/AddChassis", ReplyAction="http://tempuri.org/IChassisService/AddChassisResponse")]
    void AddChassis(CarServiceCore.Context.Sasiu chassis);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChassisService/AddChassis", ReplyAction="http://tempuri.org/IChassisService/AddChassisResponse")]
    System.Threading.Tasks.Task AddChassisAsync(CarServiceCore.Context.Sasiu chassis);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChassisService/DeleteChassis", ReplyAction="http://tempuri.org/IChassisService/DeleteChassisResponse")]
    void DeleteChassis(CarServiceCore.Context.Sasiu chassis);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChassisService/DeleteChassis", ReplyAction="http://tempuri.org/IChassisService/DeleteChassisResponse")]
    System.Threading.Tasks.Task DeleteChassisAsync(CarServiceCore.Context.Sasiu chassis);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChassisService/UpdateChassis", ReplyAction="http://tempuri.org/IChassisService/UpdateChassisResponse")]
    void UpdateChassis(CarServiceCore.Context.Sasiu chassis);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChassisService/UpdateChassis", ReplyAction="http://tempuri.org/IChassisService/UpdateChassisResponse")]
    System.Threading.Tasks.Task UpdateChassisAsync(CarServiceCore.Context.Sasiu chassis);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChassisService/PartialChassisSearch", ReplyAction="http://tempuri.org/IChassisService/PartialChassisSearchResponse")]
    CarServiceCore.Context.Sasiu[] PartialChassisSearch(CarServiceCore.Context.Sasiu chassis);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChassisService/PartialChassisSearch", ReplyAction="http://tempuri.org/IChassisService/PartialChassisSearchResponse")]
    System.Threading.Tasks.Task<CarServiceCore.Context.Sasiu[]> PartialChassisSearchAsync(CarServiceCore.Context.Sasiu chassis);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChassisService/GetAutosForChassis", ReplyAction="http://tempuri.org/IChassisService/GetAutosForChassisResponse")]
    CarServiceCore.Context.Automobil[] GetAutosForChassis(CarServiceCore.Context.Sasiu chassis);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChassisService/GetAutosForChassis", ReplyAction="http://tempuri.org/IChassisService/GetAutosForChassisResponse")]
    System.Threading.Tasks.Task<CarServiceCore.Context.Automobil[]> GetAutosForChassisAsync(CarServiceCore.Context.Sasiu chassis);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IChassisServiceChannel : IChassisService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ChassisServiceClient : System.ServiceModel.ClientBase<IChassisService>, IChassisService
{
    
    public ChassisServiceClient()
    {
    }
    
    public ChassisServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ChassisServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ChassisServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ChassisServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool ChassisExists(CarServiceCore.Context.Sasiu chassis)
    {
        return base.Channel.ChassisExists(chassis);
    }
    
    public System.Threading.Tasks.Task<bool> ChassisExistsAsync(CarServiceCore.Context.Sasiu chassis)
    {
        return base.Channel.ChassisExistsAsync(chassis);
    }
    
    public CarServiceCore.Context.Sasiu[] GetAllChassis()
    {
        return base.Channel.GetAllChassis();
    }
    
    public System.Threading.Tasks.Task<CarServiceCore.Context.Sasiu[]> GetAllChassisAsync()
    {
        return base.Channel.GetAllChassisAsync();
    }
    
    public CarServiceCore.Context.Sasiu GetChassis(int chassisId)
    {
        return base.Channel.GetChassis(chassisId);
    }
    
    public System.Threading.Tasks.Task<CarServiceCore.Context.Sasiu> GetChassisAsync(int chassisId)
    {
        return base.Channel.GetChassisAsync(chassisId);
    }
    
    public void AddChassis(CarServiceCore.Context.Sasiu chassis)
    {
        base.Channel.AddChassis(chassis);
    }
    
    public System.Threading.Tasks.Task AddChassisAsync(CarServiceCore.Context.Sasiu chassis)
    {
        return base.Channel.AddChassisAsync(chassis);
    }
    
    public void DeleteChassis(CarServiceCore.Context.Sasiu chassis)
    {
        base.Channel.DeleteChassis(chassis);
    }
    
    public System.Threading.Tasks.Task DeleteChassisAsync(CarServiceCore.Context.Sasiu chassis)
    {
        return base.Channel.DeleteChassisAsync(chassis);
    }
    
    public void UpdateChassis(CarServiceCore.Context.Sasiu chassis)
    {
        base.Channel.UpdateChassis(chassis);
    }
    
    public System.Threading.Tasks.Task UpdateChassisAsync(CarServiceCore.Context.Sasiu chassis)
    {
        return base.Channel.UpdateChassisAsync(chassis);
    }
    
    public CarServiceCore.Context.Sasiu[] PartialChassisSearch(CarServiceCore.Context.Sasiu chassis)
    {
        return base.Channel.PartialChassisSearch(chassis);
    }
    
    public System.Threading.Tasks.Task<CarServiceCore.Context.Sasiu[]> PartialChassisSearchAsync(CarServiceCore.Context.Sasiu chassis)
    {
        return base.Channel.PartialChassisSearchAsync(chassis);
    }
    
    public CarServiceCore.Context.Automobil[] GetAutosForChassis(CarServiceCore.Context.Sasiu chassis)
    {
        return base.Channel.GetAutosForChassis(chassis);
    }
    
    public System.Threading.Tasks.Task<CarServiceCore.Context.Automobil[]> GetAutosForChassisAsync(CarServiceCore.Context.Sasiu chassis)
    {
        return base.Channel.GetAutosForChassisAsync(chassis);
    }
}
