//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceCore.Context
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Automobil", Namespace="http://schemas.datacontract.org/2004/07/CarServiceCore.Context", IsReference=true)]
    public partial class Automobil : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AutoIdField;
        
        private int ClientIdField;
        
        private string NumarAutoField;
        
        private int SasiuIdField;
        
        private string SerieSasiuField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutoId
        {
            get
            {
                return this.AutoIdField;
            }
            set
            {
                this.AutoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId
        {
            get
            {
                return this.ClientIdField;
            }
            set
            {
                this.ClientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumarAuto
        {
            get
            {
                return this.NumarAutoField;
            }
            set
            {
                this.NumarAutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SasiuId
        {
            get
            {
                return this.SasiuIdField;
            }
            set
            {
                this.SasiuIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieSasiu
        {
            get
            {
                return this.SerieSasiuField;
            }
            set
            {
                this.SerieSasiuField = value;
            }
        }
    }
    
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAutoService")]
public interface IAutoService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAutosOfClient", ReplyAction="http://tempuri.org/IAutoService/GetAutosOfClientResponse")]
    CarServiceCore.Context.Automobil[] GetAutosOfClient(CarServiceCore.Context.Client client);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAutosOfClient", ReplyAction="http://tempuri.org/IAutoService/GetAutosOfClientResponse")]
    System.Threading.Tasks.Task<CarServiceCore.Context.Automobil[]> GetAutosOfClientAsync(CarServiceCore.Context.Client client);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/AutoExists", ReplyAction="http://tempuri.org/IAutoService/AutoExistsResponse")]
    bool AutoExists(CarServiceCore.Context.Automobil auto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/AutoExists", ReplyAction="http://tempuri.org/IAutoService/AutoExistsResponse")]
    System.Threading.Tasks.Task<bool> AutoExistsAsync(CarServiceCore.Context.Automobil auto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/AddAuto", ReplyAction="http://tempuri.org/IAutoService/AddAutoResponse")]
    void AddAuto(CarServiceCore.Context.Automobil auto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/AddAuto", ReplyAction="http://tempuri.org/IAutoService/AddAutoResponse")]
    System.Threading.Tasks.Task AddAutoAsync(CarServiceCore.Context.Automobil auto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/UpdateAuto", ReplyAction="http://tempuri.org/IAutoService/UpdateAutoResponse")]
    void UpdateAuto(CarServiceCore.Context.Automobil auto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/UpdateAuto", ReplyAction="http://tempuri.org/IAutoService/UpdateAutoResponse")]
    System.Threading.Tasks.Task UpdateAutoAsync(CarServiceCore.Context.Automobil auto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/DeleteAuto", ReplyAction="http://tempuri.org/IAutoService/DeleteAutoResponse")]
    void DeleteAuto(int autoId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/DeleteAuto", ReplyAction="http://tempuri.org/IAutoService/DeleteAutoResponse")]
    System.Threading.Tasks.Task DeleteAutoAsync(int autoId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetOrdersForCar", ReplyAction="http://tempuri.org/IAutoService/GetOrdersForCarResponse")]
    CarServiceCore.Context.Comanda[] GetOrdersForCar(CarServiceCore.Context.Automobil auto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetOrdersForCar", ReplyAction="http://tempuri.org/IAutoService/GetOrdersForCarResponse")]
    System.Threading.Tasks.Task<CarServiceCore.Context.Comanda[]> GetOrdersForCarAsync(CarServiceCore.Context.Automobil auto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAuto", ReplyAction="http://tempuri.org/IAutoService/GetAutoResponse")]
    CarServiceCore.Context.Automobil GetAuto(int autoId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAuto", ReplyAction="http://tempuri.org/IAutoService/GetAutoResponse")]
    System.Threading.Tasks.Task<CarServiceCore.Context.Automobil> GetAutoAsync(int autoId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAutoServiceChannel : IAutoService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AutoServiceClient : System.ServiceModel.ClientBase<IAutoService>, IAutoService
{
    
    public AutoServiceClient()
    {
    }
    
    public AutoServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AutoServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AutoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AutoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public CarServiceCore.Context.Automobil[] GetAutosOfClient(CarServiceCore.Context.Client client)
    {
        return base.Channel.GetAutosOfClient(client);
    }
    
    public System.Threading.Tasks.Task<CarServiceCore.Context.Automobil[]> GetAutosOfClientAsync(CarServiceCore.Context.Client client)
    {
        return base.Channel.GetAutosOfClientAsync(client);
    }
    
    public bool AutoExists(CarServiceCore.Context.Automobil auto)
    {
        return base.Channel.AutoExists(auto);
    }
    
    public System.Threading.Tasks.Task<bool> AutoExistsAsync(CarServiceCore.Context.Automobil auto)
    {
        return base.Channel.AutoExistsAsync(auto);
    }
    
    public void AddAuto(CarServiceCore.Context.Automobil auto)
    {
        base.Channel.AddAuto(auto);
    }
    
    public System.Threading.Tasks.Task AddAutoAsync(CarServiceCore.Context.Automobil auto)
    {
        return base.Channel.AddAutoAsync(auto);
    }
    
    public void UpdateAuto(CarServiceCore.Context.Automobil auto)
    {
        base.Channel.UpdateAuto(auto);
    }
    
    public System.Threading.Tasks.Task UpdateAutoAsync(CarServiceCore.Context.Automobil auto)
    {
        return base.Channel.UpdateAutoAsync(auto);
    }
    
    public void DeleteAuto(int autoId)
    {
        base.Channel.DeleteAuto(autoId);
    }
    
    public System.Threading.Tasks.Task DeleteAutoAsync(int autoId)
    {
        return base.Channel.DeleteAutoAsync(autoId);
    }
    
    public CarServiceCore.Context.Comanda[] GetOrdersForCar(CarServiceCore.Context.Automobil auto)
    {
        return base.Channel.GetOrdersForCar(auto);
    }
    
    public System.Threading.Tasks.Task<CarServiceCore.Context.Comanda[]> GetOrdersForCarAsync(CarServiceCore.Context.Automobil auto)
    {
        return base.Channel.GetOrdersForCarAsync(auto);
    }
    
    public CarServiceCore.Context.Automobil GetAuto(int autoId)
    {
        return base.Channel.GetAuto(autoId);
    }
    
    public System.Threading.Tasks.Task<CarServiceCore.Context.Automobil> GetAutoAsync(int autoId)
    {
        return base.Channel.GetAutoAsync(autoId);
    }
}
